<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><title>Reporte de Citas y Cobros</title>
<style>
@page{size:A4 landscape;margin:24px 28px 30px}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:8px;line-height:1.3;margin:0}.header{border-bottom:3px solid #005596;padding-bottom:9px;margin-bottom:10px}.brand{font-size:21px;font-weight:bold;color:#005596}.title{font-size:14px;font-weight:bold;text-transform:uppercase}.meta{float:right;text-align:right;color:#64748b}.clear{clear:both}.kpis{width:100%;border-collapse:collapse;margin:0 0 8px}.kpi{border:4px solid #fff;background:#f8fafc;padding:8px;width:14.28%;page-break-inside:avoid}.label{font-size:6.5px;color:#64748b;font-weight:bold;text-transform:uppercase}.value{font-size:13px;font-weight:bold;color:#0f172a;margin-top:2px}.analysis{border-left:4px solid #14b8a6;background:#f0fdfa;padding:8px 10px;margin:8px 0 12px}.section-title{background:#005596;color:#fff;padding:6px 9px;font-size:9px;font-weight:bold;text-transform:uppercase;margin-top:11px;page-break-after:avoid}table.data{width:100%;border-collapse:collapse;margin-top:6px;page-break-before:auto;page-break-after:auto}table.data thead{display:table-header-group}table.data tbody{display:table-row-group}table.data tr{page-break-inside:avoid;page-break-after:auto}table.data th{background:#e2e8f0;border:1px solid #cbd5e1;padding:4px 3px;text-align:left;font-size:6.4px;text-transform:uppercase}table.data td{border:1px solid #e2e8f0;padding:4px 3px;vertical-align:top}table.data tr:nth-child(even) td{background:#f8fafc}.right{text-align:right}.center{text-align:center}.money{white-space:nowrap;font-weight:bold;color:#047857}.muted{color:#64748b}.section-separator{height:12px;border-bottom:1px solid #dbe4ee;margin-bottom:10px}.footer{margin-top:14px;border-top:1px solid #cbd5e1;padding-top:4px;color:#64748b;font-size:6.5px}.footer span{float:right}
</style></head><body>
@php $s=$report['summary']; $money=fn($v)=>'L '.number_format((float)$v,2,'.',','); @endphp
<div class="header"><div class="meta">REGISTROS: {{ $s['total_citas'] }}<br>GENERADO: {{ $report['meta']['generated_at'] }}</div><div class="brand">MedGo+</div><div class="title">Reporte Ejecutivo y Contable de Citas y Cobros</div><div class="clear"></div></div>
<table class="kpis"><tr>
<td class="kpi"><div class="label">Total citas</div><div class="value">{{ $s['total_citas'] }}</div></td><td class="kpi"><div class="label">Completadas</div><div class="value">{{ $s['completadas'] }}</div></td><td class="kpi"><div class="label">Canceladas</div><div class="value">{{ $s['canceladas'] }}</div></td><td class="kpi"><div class="label">Con cobro</div><div class="value">{{ $s['con_pago'] }}</div></td><td class="kpi"><div class="label">Recaudación</div><div class="value">{{ $money($s['monto_cobrado']) }}</div></td><td class="kpi"><div class="label">Ticket promedio</div><div class="value">{{ $money($s['ticket_promedio']) }}</div></td><td class="kpi"><div class="label">Tasa cobro</div><div class="value">{{ number_format($s['tasa_cobro'],1) }}%</div></td>
</tr></table>
<div class="analysis"><strong>Lectura ejecutiva:</strong> {{ $report['interpretation'] }}</div>
<div class="section-title">Resumen contable por médico</div>
<table class="data"><thead><tr><th>Médico</th><th class="center">Citas</th><th class="right">Cobrado</th><th class="right">Participación</th></tr></thead><tbody>
@forelse($report['analytics']['por_doctor'] as $row)<tr><td>{{ $row['doctor'] }}</td><td class="center">{{ $row['citas'] }}</td><td class="right money">{{ $money($row['cobrado']) }}</td><td class="right">{{ $s['monto_cobrado'] > 0 ? number_format(($row['cobrado']/$s['monto_cobrado'])*100,1) : '0.0' }}%</td></tr>@empty<tr><td colspan="4" class="center muted">Sin información para el período.</td></tr>@endforelse
</tbody></table>
<div class="section-title">Recaudación mensual</div><table class="data"><thead><tr><th>Período</th><th class="right">Monto cobrado</th></tr></thead><tbody>@foreach($report['analytics']['recaudacion_mensual'] as $row)<tr><td>{{ $row['periodo'] }}</td><td class="right money">{{ $money($row['monto']) }}</td></tr>@endforeach</tbody></table>
<div class="section-separator"></div><div class="section-title">Detalle auditable de citas, atención y cobros</div>
<table class="data"><thead><tr><th>Cita / fecha</th><th>Estado</th><th>Paciente</th><th>Médico / entidad</th><th>Consulta / diagnóstico</th><th class="right">Cobrado</th><th>Pago</th></tr></thead><tbody>
@forelse($report['data'] as $row)<tr><td><strong>#{{ $row['CitaID'] }}</strong><br>{{ $row['FechaHora'] }}</td><td>{{ $row['EstadoCita'] }}</td><td>{{ $row['Paciente'] }}<br><span class="muted">{{ $row['DNI'] ?: 'Sin DNI' }}</span></td><td>{{ $row['Doctor'] }}<br><span class="muted">{{ $row['Entidad'] ?: 'Sin entidad' }}</span></td><td>{{ $row['ConsultaID'] ? '#'.$row['ConsultaID'] : 'Sin consulta' }}<br>{{ $row['Diagnostico'] ?: 'Sin diagnóstico' }}</td><td class="right money">{{ $money($row['MontoCobrado']) }}</td><td>{{ $row['MetodosPago'] ?: 'Sin pago' }}<br><span class="muted">{{ $row['EstadosPago'] ?: 'No aplica' }}</span></td></tr>@empty<tr><td colspan="7" class="center muted">No hay registros para los filtros seleccionados.</td></tr>@endforelse
</tbody></table><div class="footer">MedGo+ Global - Documento administrativo confidencial <span>{{ $report['meta']['generated_at'] }}</span></div></body></html>
